// Operation: an intentional mutation of the model (ADR-0008, ADR-0019).
//
// An Operation is data, not behaviour. It exists so a mutation can later be replicated,
// recorded, undone, attributed or arbitrated — the network is one destination among
// several, never the definition.
//
// Only setProperty() and its structural siblings create Operations. A plain write
// (`object.x = 100`) is a simulation output, not an intent, and produces none.
//
// WHAT EVERY OPERATION CARRIES, AND WHY IT IS SPLIT IN TWO.
//
//   what it takes to APPLY      type, target, and the new state
//   what it takes to INVERT     `previous`, `previousParent`, `previousIndex`, `values`,
//                               `subtree`
//
// The second group is what makes undo a consequence of the format rather than a feature
// bolted on top (ADR-0024). It also makes the payload heavier — ADR-0008 says so — and it
// is deliberately *separable*: a transport is free to prune the inversion fields, since a
// receiver never needs them to apply. That pruning is not built here; the format only has
// to make it possible, and naming the fields is what does.
//
// IDENTIFIERS ARE GENERATED BY THE AUTHOR and travel in the payload. A receiver that
// minted its own would make two machines disagree about which object is which.

export const OperationType = {
    SET_PROPERTY: 'SET_PROPERTY',

    // Scene scope.
    ADD_OBJECT: 'ADD_OBJECT',
    REMOVE_OBJECT: 'REMOVE_OBJECT',
    ADD_COMPONENT: 'ADD_COMPONENT',
    REMOVE_COMPONENT: 'REMOVE_COMPONENT',
    MOVE_COMPONENT: 'MOVE_COMPONENT',
    /**
     * One operation for four gestures: reparent, unparent (`parent: null`), reorder among
     * siblings, and reorder among the scene's roots. They are the same mutation — a drop
     * between two rows changes the parent AND the position, atomically — and splitting
     * them would produce operations that must always travel together, undo together, and
     * in the right order (ADR-0019).
     */
    REPARENT: 'REPARENT',

    // Project scope: a second pipeline, same machine (ADR-0020).
    ADD_RESOURCE: 'ADD_RESOURCE',
    REMOVE_RESOURCE: 'REMOVE_RESOURCE',
    /**
     * The manifest's `REPARENT`: one operation for filing a resource in another folder AND
     * for ranking it among its siblings (ADR-0026). The argument is the one ADR-0019 makes
     * for objects — a drop between two rows changes the folder and the position at once,
     * and the inverse of a move is a move.
     */
    MOVE_RESOURCE: 'MOVE_RESOURCE',

    // `.px` scope: a third pipeline, same machine (ADR-0027). A Component definition and
    // the graph it carries are ONE resource, so they share one pipeline and therefore one
    // undo stack — which is the whole reason there is no operation here for "save the
    // payload": what is undoable is each edit, not the write.
    //
    // ONLY WHAT THE FORMAT COULD NOT ALREADY SAY. Moving a node, changing one of its
    // params, renaming a declared property, changing its type or its default: every one of
    // those is a field of a reactive record, so every one of them is `SET_PROPERTY`, which
    // replicates and inverts already. What is left is what genuinely appears and
    // disappears.
    ADD_NODE: 'ADD_NODE',
    REMOVE_NODE: 'REMOVE_NODE',
    CONNECT: 'CONNECT',
    DISCONNECT: 'DISCONNECT',

    // The user-declared properties of a Component definition. A property is not a value
    // held by an instance — it is a line of the SCHEMA — so it appears and disappears
    // through its own pair, and is edited through SET_PROPERTY like everything else.
    ADD_PROPERTY: 'ADD_PROPERTY',
    REMOVE_PROPERTY: 'REMOVE_PROPERTY'
};

/**
 * Build an Operation.
 *
 * `seq` is left null unless a caller supplies one: the pipeline stamps it on submit, so a
 * sequence number belongs to the pipeline that arbitrated the operation rather than to the
 * process that happened to build it (ADR-0019).
 *
 * @param {object} spec - Operation fields
 * @param {string} spec.type - One of OperationType
 * @param {object} spec.target - { object: id, component: type name or null }
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it, for authority and attribution
 * @param {string} [spec.batch] - Groups related operations into one history entry
 * @param {number} [spec.seq] - Sequence number; stamped by the pipeline when omitted
 * @returns {object} A frozen Operation
 */
export function createOperation({ type, target, origin, actor = null, batch = null, seq = null, ...payload }) {
    if (!type) throw new TypeError('createOperation: type is required');
    if (!target?.object) throw new TypeError('createOperation: target.object is required');
    if (!origin) throw new TypeError('createOperation: origin is required');

    return globalThis.Object.freeze({
        type,
        target: globalThis.Object.freeze({ object: target.object, component: target.component ?? null }),
        origin,
        actor,
        batch,
        seq,
        ...payload
    });
}

/**
 * Build a SET_PROPERTY operation.
 * @param {object} spec - Operation fields
 * @param {object} spec.target - { object: id, component: type name or null }
 * @param {string} spec.prop - Property name
 * @param {any} spec.value - New value
 * @param {any} spec.previous - Value before the change, which is what makes undo possible
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function setPropertyOperation({ target, prop, value, previous, origin, actor, batch }) {
    return createOperation({
        type: OperationType.SET_PROPERTY,
        target,
        prop,
        value,
        previous,
        origin,
        actor,
        batch
    });
}

/**
 * Build an ADD_OBJECT operation.
 *
 * The object travels serialized, identifier included, so every node builds the same object
 * with the same id. `index` is what makes undoing a deletion put the object back where it
 * was rather than at the end of the list.
 *
 * @param {object} spec - Operation fields
 * @param {object} spec.object - The serialized object, as serializeObject() produces it
 * @param {string|null} [spec.parent] - Parent identifier, or null for a root
 * @param {number} [spec.index] - Rank among its siblings, or among the roots
 * @param {object[]} [spec.subtree] - Serialized descendants, restored with it
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function addObjectOperation({ object, parent = null, index = null, subtree = [], origin, actor, batch }) {
    return createOperation({
        type: OperationType.ADD_OBJECT,
        target: { object: object.id, component: null },
        object,
        parent,
        index,
        subtree,
        origin,
        actor,
        batch
    });
}

/**
 * Build a REMOVE_OBJECT operation.
 *
 * `subtree`, `parent` and `index` are the inversion fields. Without them, undoing a
 * deletion returns a stripped object at the end of the list — which is the difference
 * between an undo and an apology.
 *
 * @param {object} spec - Operation fields
 * @param {object} spec.object - The serialized object being removed
 * @param {object[]} [spec.subtree] - Its serialized descendants
 * @param {string|null} [spec.parent] - The parent it hung from
 * @param {number} [spec.index] - The rank it held
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function removeObjectOperation({ object, subtree = [], parent = null, index = null, origin, actor, batch }) {
    return createOperation({
        type: OperationType.REMOVE_OBJECT,
        target: { object: object.id, component: null },
        object,
        subtree,
        parent,
        index,
        origin,
        actor,
        batch
    });
}

/**
 * Build an ADD_COMPONENT operation.
 * @param {object} spec - Operation fields
 * @param {string} spec.object - Identifier of the object to attach to
 * @param {string} spec.component - The component type name
 * @param {number} [spec.index] - Rank in the ordered collection
 * @param {object} [spec.values] - The component's serialized values
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function addComponentOperation({ object, component, index = null, values = {}, origin, actor, batch }) {
    return createOperation({
        type: OperationType.ADD_COMPONENT,
        // The target names the object: the component slot does not exist yet, so it
        // cannot be resolved. `component` in the payload says which type is arriving.
        target: { object, component: null },
        component,
        index,
        values,
        origin,
        actor,
        batch
    });
}

/**
 * Build a REMOVE_COMPONENT operation.
 *
 * `values` is what stops "remove then undo" from returning a component reset to its
 * defaults — the measured `42 -> 1` of the Phase 1 audit.
 *
 * @param {object} spec - Operation fields
 * @param {string} spec.object - Identifier of the object to detach from
 * @param {string} spec.component - The component type name
 * @param {number} [spec.index] - The rank it held
 * @param {object} [spec.values] - Its serialized values
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function removeComponentOperation({ object, component, index = null, values = {}, origin, actor, batch }) {
    return createOperation({
        type: OperationType.REMOVE_COMPONENT,
        target: { object, component: null },
        component,
        index,
        values,
        origin,
        actor,
        batch
    });
}

/**
 * Build a MOVE_COMPONENT operation.
 * @param {object} spec - Operation fields
 * @param {string} spec.object - Identifier of the object
 * @param {string} spec.component - The component type name
 * @param {number} spec.index - The rank to move it to
 * @param {number} spec.previousIndex - The rank it held
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function moveComponentOperation({ object, component, index, previousIndex, origin, actor, batch }) {
    return createOperation({
        type: OperationType.MOVE_COMPONENT,
        target: { object, component: null },
        component,
        index,
        previousIndex,
        origin,
        actor,
        batch
    });
}

/**
 * Build a REPARENT operation.
 *
 * The scene's roots are the children of an implicit `null` parent, so reordering a root is
 * `REPARENT { parent: null, index }`. One model, one operation, one inverse.
 *
 * @param {object} spec - Operation fields
 * @param {string} spec.object - Identifier of the object being moved
 * @param {string|null} spec.parent - The new parent's identifier, or null for a root
 * @param {number} [spec.index] - Rank among the new siblings
 * @param {string|null} spec.previousParent - The parent it hung from
 * @param {number} [spec.previousIndex] - The rank it held
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function reparentOperation({
    object,
    parent = null,
    index = null,
    previousParent = null,
    previousIndex = null,
    origin,
    actor,
    batch
}) {
    return createOperation({
        type: OperationType.REPARENT,
        target: { object, component: null },
        parent,
        index,
        previousParent,
        previousIndex,
        origin,
        actor,
        batch
    });
}

/**
 * Build an ADD_RESOURCE operation, for the Project pipeline (ADR-0020).
 * @param {object} spec - Operation fields
 * @param {object} spec.resource - The manifest entry
 * @param {any} [spec.payload] - The resource's content
 * @param {number} [spec.index] - Rank in the manifest
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function addResourceOperation({ resource, payload = null, index = null, origin, actor, batch }) {
    return createOperation({
        type: OperationType.ADD_RESOURCE,
        target: { object: resource.id, component: null },
        resource,
        payload,
        index,
        origin,
        actor,
        batch
    });
}

/**
 * Build a MOVE_RESOURCE operation, for the Project pipeline (ADR-0026).
 *
 * `index` is a rank AMONG SIBLINGS, never a position in the flat manifest: a creator drops
 * a row between two rows of the folder they are looking at, and a global position would
 * mean something different on every machine whose manifest grew differently.
 *
 * @param {object} spec - Operation fields
 * @param {string} spec.resource - The ResourceId being moved
 * @param {string|null} [spec.parent] - The destination folder, or null for the top level
 * @param {number|null} [spec.index] - Rank among the destination's children; appended when null
 * @param {string|null} [spec.previousParent] - The folder it was in
 * @param {number|null} [spec.previousIndex] - The rank it held
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function moveResourceOperation({
    resource,
    parent = null,
    index = null,
    previousParent = null,
    previousIndex = null,
    origin,
    actor,
    batch
}) {
    return createOperation({
        type: OperationType.MOVE_RESOURCE,
        target: { object: resource, component: null },
        parent,
        index,
        previousParent,
        previousIndex,
        origin,
        actor,
        batch
    });
}

/**
 * Build a REMOVE_RESOURCE operation, for the Project pipeline (ADR-0020).
 * @param {object} spec - Operation fields
 * @param {object} spec.resource - The manifest entry being removed
 * @param {any} [spec.payload] - Its content, so the removal can be undone
 * @param {number} [spec.index] - The rank it held
 * @param {string} spec.origin - One of Origin
 * @param {string} [spec.actor] - Who authored it
 * @param {string} [spec.batch] - History grouping
 * @returns {object} A frozen Operation
 */
export function removeResourceOperation({ resource, payload = null, index = null, origin, actor, batch }) {
    return createOperation({
        type: OperationType.REMOVE_RESOURCE,
        target: { object: resource.id, component: null },
        resource,
        payload,
        index,
        origin,
        actor,
        batch
    });
}
